backbone:
  _target_: tensorflow.keras.applications.MobileNetV3Large
  input_shape: null
  alpha: 1.0
  minimalistic: false
  include_top: false
  weights: imagenet
  input_tensor: null
  classes: 1000
  pooling: null
  dropout_rate: 0.2
  classifier_activation: softmax
  include_preprocessing: true
