defaults: # these are the sub-config files for specific details
  - _self_ # this makes the top-level config take priority over sub-configs, see https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/
  - backbones: backbone
  - optimizer: optimizer_adam
  - loss: loss
  - metrics: metrics
general:
  experiment_name: "???"
  output_dir: "???"
  batch_size: 256
  num_epochs: 500
  seed: 0
  freeze_backbone: true
  multi_gpu_training: false
  dataset_path: /home/saumya.saksena/Downloads/Datasets/Stanford40/JPEGImages/
  image_splits_path: /home/saumya.saksena/Downloads/Datasets/Stanford40/ImageSplits
  train_val_split_ratio: 0.9

dataloader:
  input_shape: [400, 400, 3]
  num_classes: 40
  normalize: false

callbacks:
  monitor_metric: val_accuracy
  mode: max
  lr_reduction_factor: 0.9
  lr_reduction_patience: 50
  early_stopping_patience: 50
  min_delta: 0.0
  min_lr: 1e-6

stanford40_class_names:
  {
    "applauding": 0,
    "blowing_bubbles": 1,
    "brushing_teeth": 2,
    "cleaning_the_floor": 3,
    "climbing": 4,
    "cooking": 5,
    "cutting_trees": 6,
    "cutting_vegetables": 7,
    "drinking": 8,
    "feeding_a_horse": 9,
    "fishing": 10,
    "fixing_a_bike": 11,
    "fixing_a_car": 12,
    "gardening": 13,
    "holding_an_umbrella": 14,
    "jumping": 15,
    "looking_through_a_microscope": 16,
    "looking_through_a_telescope": 17,
    "phoning": 18,
    "playing_guitar": 19,
    "playing_violin": 20,
    "pouring_liquid": 21,
    "pushing_a_cart": 22,
    "reading": 23,
    "riding_a_bike": 24,
    "riding_a_horse": 25,
    "rowing_a_boat": 26,
    "running": 27,
    "shooting_an_arrow": 28,
    "smoking": 29,
    "taking_photos": 30,
    "texting_message": 31,
    "throwing_frisby": 32,
    "using_a_computer": 33,
    "walking_the_dog": 34,
    "washing_dishes": 35,
    "watching_TV": 36,
    "waving_hands": 37,
    "writing_on_a_board": 38,
    "writing_on_a_book": 39,
  }
